<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['country' => 'Afghanistan', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Albania', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Algeria', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Andorra', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Angola', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Antigua and Barbuda', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Argentina', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Armenia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Australia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Austria', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Azerbaijan', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Bahamas', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Bahrain', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Bangladesh', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Barbados', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Belarus', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Belgium', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Belize', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Benin', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Bhutan', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Bolivia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Bosnia and Herzegovina', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Botswana', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Brazil', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Brunei Darussalam', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Bulgaria', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Burkina Faso', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Burundi', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Cabo Verde', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Cambodia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Cameroon', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Canada', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Central African Republic', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Chad', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Chile', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'China', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Colombia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Comoros', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Congo (Congo-Brazzaville)', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Congo (Democratic Republic of the Congo)', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Costa Rica', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Croatia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Cuba', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Cyprus', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Czech Republic (Czechia)', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Denmark', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Djibouti', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Dominica', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Dominican Republic', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Ecuador', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Egypt', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'El Salvador', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Equatorial Guinea', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Eritrea', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Estonia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Eswatini', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Ethiopia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Fiji', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Finland', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'France', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Gabon', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Gambia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Georgia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Germany', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Ghana', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Greece', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Grenada', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Guatemala', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Guinea', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Guinea-Bissau', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Guyana', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Haiti', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Honduras', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Hungary', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Iceland', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'India', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Indonesia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Iran', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Iraq', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Ireland', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Israel', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Italy', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Jamaica', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Japan', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Jordan', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Kazakhstan', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Kenya', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Kiribati', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Korea (North)', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Korea (South)', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Kuwait', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Kyrgyzstan', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Laos', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Latvia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Lebanon', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Lesotho', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Liberia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Libya', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Liechtenstein', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Lithuania', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Luxembourg', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Madagascar', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Malawi', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Malaysia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Maldives', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Mali', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Malta', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Marshall Islands', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Mauritania', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Mauritius', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Mexico', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Micronesia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Moldova', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Monaco', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Mongolia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Montenegro', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Morocco', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Mozambique', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Myanmar (Burma)', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Namibia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Nauru', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Nepal', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Netherlands', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'New Zealand', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Nicaragua', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Niger', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Nigeria', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'North Macedonia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Norway', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Oman', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Pakistan', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Palau', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Panama', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Papua New Guinea', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Paraguay', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Peru', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Philippines', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Poland', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Portugal', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Qatar', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Romania', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Russia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Rwanda', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Saint Kitts and Nevis', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Saint Lucia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Saint Vincent and the Grenadines', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Samoa', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'San Marino', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Sao Tome and Principe', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Saudi Arabia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Senegal', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Serbia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Seychelles', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Sierra Leone', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Singapore', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Slovakia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Slovenia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Solomon Islands', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Somalia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'South Africa', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'South Sudan', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Spain', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Sri Lanka', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Sudan', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Suriname', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Sweden', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Switzerland', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Syria', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Taiwan', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Tajikistan', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Tanzania', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Thailand', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Timor-Leste', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Togo', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Tonga', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Trinidad and Tobago', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Tunisia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Turkey', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Turkmenistan', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Tuvalu', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Uganda', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Ukraine', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'United Arab Emirates', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'United Kingdom', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'United States', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Uruguay', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Uzbekistan', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Vanuatu', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Vatican City', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Venezuela', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Vietnam', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Yemen', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Zambia', 'currency' => 'USD', 'status' => 'active'],
            ['country' => 'Zimbabwe', 'currency' => 'USD', 'status' => 'active'],
        ];

        // Insert countries into the database
        DB::table('countries')->insert($countries);
    }
}
